### PR TITLE
Changes for Dutch

### PR DESCRIPTION
**Pull request by petermorlion**
This should address points 1 and 4 from issue #181:

- Selecting Dutch (Netherlands) now also changes the UI to Dutch. I've used one resource file as written Dutch doesn't differ that much between the Netherlands and Belgium.
- Some resources were split over multiple lines so the hovertext for keys can increase.

### CODE REVIEW

**Comment by JuliusSweetland** [comment]
Hi Peter,

I have merged in the latest changes from my master branch into my Dutch branch, which includes Russian and all the new changes for v2.2.2.

I spent a couple of minutes looking over the new Belgian changes. Looks good. I think the strings are still too small. The longest strings that I can see on the Alpha keyboard are the "add to dictionary" and "diacritics" strings. Perhaps they could be broken over another line?

Also I am not sure why, but I cannot merge in this pull request? Could you rebase against Optikey/Dutch and try to create a new pull request? Make sure you get latest from Dutch

Thanks,
Julius

**Comment by petermorlion** [comment]
Hi Julius, I think I needed to confirm the merge first? I'm doing this for the first time, but I just clicked on a button to confirm the merge and now I see the message 'petermorlion merged commit d9576bc into OptiKey/Dutch a minute ago'. I'm confused as I thought you would have to confirm the merge.

Anyway, I'll pull the latest changes into my fork/branch and see if I can split up the hovertexts further.

**Comment by petermorlion** [comment]
Ah, that might be the merge to my forked Dutch branch.

**Comment by JuliusSweetland** [comment]
Yes I was going to say that. I suspect you're meeting between your own
branches

**Pull request merged**
